name: Deploy to Server

on:
  push:
    branches:
      - main  # This workflow will run when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        ssh-host: ${{ secrets.SERVER_IP }}

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.PROJECT_PATH }} && ./plep.sh"