name: Deploy to Server

on:
  push:
    branches:
      - main  # This workflow will run when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "Deployment started"
        LASTSSH: "Deployment finished"
      with:
        host: ${{ secrets.SERVER_IP }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASSWORD }}
        connect_timeout: 10s
        script: |
          echo $WELCOME
          cd ${{ secrets.PROJECT_PATH }}
          git pull && pnpm install && pnpm run build && cp -r /home/thomas/caption-youtube/node_modules/ffmpeg-static/ /home/thomas/caption-youtube/.output/server/node_modules && pm2 startOrRestart YTSubs
          echo $LASTSSH